name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Build release
        run: cargo build --release
        
      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: s3-cas-linux
          path: target/release/s3-cas
          
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Build release
        run: cargo build --release
        
      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: s3-cas-macos
          path: target/release/s3-cas
          
  create-release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: List directories
        run: |
          ls -la
          ls -la artifacts
          ls -la artifacts/s3-cas-linux || echo "Linux directory not found"
          ls -la artifacts/s3-cas-macos || echo "macOS directory not found"
        
      - name: Rename binaries to include platform
        run: |
          if [ -f "artifacts/s3-cas-linux/s3-cas" ]; then
            mv artifacts/s3-cas-linux/s3-cas artifacts/s3-cas-linux/s3-cas-linux
          fi
          if [ -f "artifacts/s3-cas-macos/s3-cas" ]; then
            mv artifacts/s3-cas-macos/s3-cas artifacts/s3-cas-macos/s3-cas-macos
          fi
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/s3-cas-linux/s3-cas-linux
            artifacts/s3-cas-macos/s3-cas-macos